language: objective-c
script:
  - xctool -project animalchess.xcodeproj -scheme animalchess -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project animalchess.xcodeproj -scheme animalchess -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
